### ISSUE TITLE
Visual Studio 17.8.0 hangs with version 	1.4.8

### ISSUE THREAD

**Issue by danielcandea** [belav/csharpier#1026]
I did a fresh install of Windows 11 build 22621.2715, installed CSharpier plugin 1.4.8 and Visual Studio hangs after a few seconds after opening a solution.
 
I can reproduce this every time with CSharpier being the only plugin installed. Once I uninstall it and add my usual ones everything works fine.

**Comment by belav** [comment]
If you are using CSharpier 0.26.* (which would happen if you are clicking install globally/locally) then this is probably the same issue that is occurring across all of the IDEs. I'm hoping to be able to track it down soon.

As a workaround you can install csharpier 0.25.0 outside of the plugin.

**Comment by belav** [comment]
I have a few questions, I think most other people are experiencing complete freezes that VS doesn't recover from.

Does VS go back to normal after a few seconds or is it a complete freeze?
Does switching to 0.25.0 make the problem go away.
Are you able to format any files?
Could you share what is in the output window for CSharpier? Turning on log debug messages first will give more info.

**Comment by danielcandea** [comment]
VS doesn't recover, it remains like that. But it isn't like "Not Responding" freeze, being greyed out, more like there is an invisible dialog window preventing clicks and scrolling. Clicking VS icon in the taskbar doesn't do anything either.

I can't do anything past VS opening the solution, not seeing output, not opening a file or format an existing one. The only way to uninstall the plugin was to open VS without code.

I downgraded to 0.25.0 and the plugin seems fine again.

**Comment by belav** [comment]
I believe I know a way to resolve the problem, see https://github.com/belav/csharpier/issues/926#issuecomment-1817939428 for more details

**Comment by danielcandea** [comment]
That didn't solve the issue, but while going through issue I saw that duplicate lines in .editorconfig might cause problems so I checked it and had some duplicates. I removed them and things seem fine now, csharpier installed globally, v0.26.2 and the VS plugin v1.4.8.

**Comment by IT-CASADO** [comment]
I'm facing the same issue with v0.26.2 and the VS plugin v1.4.8.
My .editorconfig doesn't have any duplicates and the mentioned workarond by @belav doesn't help.

This ticket should be re-opened.

**Comment by IT-CASADO** [comment]
Seems to be fixed with version v0.26.3 :)

**Comment by IT-CASADO** [comment]
This is not fixed. VS hangs regularly on my machine and for colleagues.

If that happens I can see CPU spikes forced by CSharpier:

<img width="603" alt="image" src="https://github.com/belav/csharpier/assets/2911693/9a58840c-458d-4f50-a3e6-4be4e5d38dd6">

If I wait for a long time (or kill the CSharpier task in Task Manager) I'm ending with #1072.
This is very frustrating.

I tried the troubleshooting guide multiple times, but it doesn't help.

**Comment by danielcandea** [comment]
Started happening again, slightly differently for me as well, every time I open Visual Studio I get a message that it stopped responding for about 15-20 seconds, afterwards it seems fine.
I am using Visual Studio 17.8.3, plugin 1.4.8 and the tool is at 0.26.6.

**Comment by IT-CASADO** [comment]
For me sometimes it's still working after the 'stopped responding' message.

I very often open Visual Studio and VS Studio Code at the same time. I think in this case CSharpier is broken in Visual Studio after the message. But this is only a feeling...

In Visual Studio Code I don't get any issues so far.

**Comment by Kurren123** [comment]
Happening to me too. No .editorconfig file, I enable debug log messages and get this:

```
Starting
Ensure there is a csharpier process for C:\dev\PBI-SQLService
Looking for C:\dev\PBI-SQLService\.config/dotnet-tools.json
Looking for C:\dev\.config/dotnet-tools.json
Looking for C:\.config/dotnet-tools.json
Unable to find dotnet-tools.json, falling back to running dotnet csharpier --version
dotnet csharpier --version output: 0.26.7+c8aec144f227bda8cf195011e9d91bb36c33337f
Removing everything after + to use 0.26.7
dotnet csharpier --version output: 0.26.7+c8aec144f227bda8cf195011e9d91bb36c33337f
Adding new version 0.26.7 process for C:\dev\PBI-SQLService
Warm CSharpier with initial format
CSharpier process appears to be hung, restarting it.
Warm CSharpier with initial format
```

**Comment by belav** [comment]
I resolved a number of issues with the new 1.5.0 version of the extension. It also has better logging and notification when it is unable to start the CSharpier process.

Let me know if there are still issues!

**Comment by danielcandea** [comment]
I've updated the plugin to 1.5.0 with the tool at 0.26.6 and had no issues after opening a few solutions.
Next, I've updated the tool to 0.26.7 and got one hang after opening a solution, but couldn't reproduce it afterwards after several tries.

**Comment by Kurren123** [comment]
> I resolved a number of issues with the new 1.5.0 version of the extension. It also has better logging and notification when it is unable to start the CSharpier process.
> 
> Let me know if there are still issues!

Thanks so much, it no longer hangs. However I am getting this on every load of visual studio:

```
[Info - 17/12/2023 23:17:15] Starting
[Error - 17/12/2023 23:17:16] System.NullReferenceException: Object reference not set to an instance of an object.
   at CSharpier.VisualStudio.ReformatWithCSharpierOnSave.FindDocument(UInt32 docCookie)
```

**Comment by IT-CASADO** [comment]
In general this seems to work now :)

Visual Studio is not hanging for a long time, but I still get this message: "Visual Studio stopped responding for x seconds"

<img width="822" alt="image" src="https://github.com/belav/csharpier/assets/2911693/db4ad3b5-be14-4230-a31f-8bd2d85b88f9">

But everything is working so far.

In the log I can see a warning ("CSharpier process appears to be hung, restarting it.")
and sometimes an error ("Object reference not set to an instance of an object."):

My Log:
```
[Info - 19.12.2023 08:59:57] Starting
[Debug - 19.12.2023 08:59:58] Ensure there is a csharpier process for xxx/Report\Service\Evo.ReportEngine.Service.Job
[Debug - 19.12.2023 08:59:58] Looking for xxx/Report\Service\Evo.ReportEngine.Service.Job\.config/dotnet-tools.json
[Debug - 19.12.2023 08:59:58] Looking for xxx/Report\Service\.config/dotnet-tools.json
[Debug - 19.12.2023 08:59:58] Looking for xxx/Report\.config/dotnet-tools.json
[Debug - 19.12.2023 08:59:58] Looking for xxx/.config/dotnet-tools.json
[Debug - 19.12.2023 08:59:58] Looking for xxx\.config/dotnet-tools.json
[Debug - 19.12.2023 08:59:58] Found version 0.26.7 in xxx\.config/dotnet-tools.json
[Debug - 19.12.2023 08:59:59] dotnet csharpier --version output: 0.26.7+c8aec144f227bda8cf195011e9d91bb36c33337f
[Debug - 19.12.2023 08:59:59] Using 0.26.7 as the version number.
[Debug - 19.12.2023 08:59:59] CSharpier at C:\Users\CasadoDaniel\AppData\Local\CSharpier\0.26.7 already exists
[Debug - 19.12.2023 08:59:59] Adding new version 0.26.7 process for xxx/Report\Service\Evo.ReportEngine.Service.Job
[Debug - 19.12.2023 08:59:59] Warm CSharpier with initial format
[Warn - 19.12.2023 09:00:02] CSharpier process appears to be hung, restarting it.
[Warn - 19.12.2023 09:00:05] CSharpier process appears to be hung, restarting it.
cture
[Error - 19.12.2023 09:00:51] System.NullReferenceException: Object reference not set to an instance of an object.
   at CSharpier.VisualStudio.ReformatWithCSharpierOnSave.FindDocument(UInt32 docCookie)
```

**Comment by belav** [comment]
I believe I have the occasional NRE fixed and am releasing 1.5.1 for that.

The initial hang some people are seeing is probably csharpier being installed in the background. I think this could be avoided by converting a lot of this code to async, but it should be only occuring once when using a new version of csharpier so I'm not sure it is worth the effort.

I've managed to reproduce getting CSharpier to hang and restart itself.

- add a bunch of compilation errors to a file
- make change and save
- repeat until it hangs

Rider had a similar problem, but the fix in Rider (java based) doesn't seem to apply to VS. I'll dig into that a bit more.

@IT-CASADO are you seeing the "Visual Studio stopped responding for X seconds" message regularly? It also seems like the initial warming of csharpier is hanging for you, which I have not seem before. The warming process is a simple c# class, so I can't see why it would be causing things to hang.

I do have a reworking of the communication between the extensions and csharpier using GRPC almost ready, and I am hoping that will resolve some of the flakeiness with piping input/output to csharpier.

**Comment by parched** [comment]
I've been getting this a bit recently. I'm not sure exactly when it triggers, but I think it's when there is compilation errors.
![image](https://github.com/belav/csharpier/assets/5975405/23db8480-1c95-49f7-8013-7649b217104d)

**Comment by mejobloggs** [comment]
> I've been getting this a bit recently. I'm not sure exactly when it triggers, but I think it's when there is compilation errors. ![image](https://private-user-images.githubusercontent.com/5975405/295490686-23db8480-1c95-49f7-8013-7649b217104d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTA0NDQsIm5iZiI6MTcwNjA5MDE0NCwicGF0aCI6Ii81OTc1NDA1LzI5NTQ5MDY4Ni0yM2RiODQ4MC0xYzk1LTQ5ZjctODAxMy03NjQ5YjIxNzEwNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMDk1NTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzZlMTZlZWQyYzU0ZTM5NDc3NTRjODZhNmU1Y2Q1ZjAzNzUzODg1OWRmODI3ZjcwNDU1ODUyNDU4NzJjNzY2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nqoAyjbqxoLRCNwxJtqJs16Vb4LqXntZzm28yV0QUOg)

Same here, I get this most times I open Visual Studio

**Comment by ceisele-r** [comment]
For me, it's happening every time I open Visual Studio and afterwards open a C# file in the solution.

So to reproduce:

1. open a Visual Studio C# solution -> all good for now.
2. Then open a C# file, Visual Studio hangs for 10-20 Seconds and the yellow bar appears.

In contrast to @parched 's assumption, there are no compile errors in my solution.
